<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! - Open Source Content Management" -->
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="pt-br">
	<title type="text">Notícias - REINTER - Secretaria de Relações Internacionais</title>
	<subtitle type="text">Assessoria de Relações Internacionais - Universidade Federal do Rio Grande - FURG</subtitle>
	<link rel="alternate" type="text/html" href="https://reinter2.furg.br"/>
	<id>https://reinter2.furg.br/index.php</id>
	<updated>2025-06-09T16:08:07-03:00</updated>
	<generator uri="https://www.joomla.org">Joomla! - Open Source Content Management</generator>
	<link rel="self" type="application/atom+xml" href="https://reinter2.furg.br/index.php?option=com_content&amp;view=category&amp;id=24&amp;Itemid=137&amp;format=feed&amp;type=atom"/>
	<entry>
		<title>A convocatória do projeto Euro-Brazilian Windows + ainda está aberta</title>
		<link rel="alternate" type="text/html" href="https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=42&amp;catid=24&amp;Itemid=137"/>
		<published>2016-08-05T12:08:23-03:00</published>
		<updated>2016-08-05T12:08:23-03:00</updated>
		<id>https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=42&amp;catid=24&amp;Itemid=137</id>
		<summary type="html">&lt;p&gt;O projeto Euro-Brazilian Windows + tem &amp;nbsp;o apoio financeiro atribuído pela Comissão Europeia através do Programa Erasmus Mundus e oferece bolsas a estudantes, pesquisadores e pessoal acadêmico e administrativo do Brasil que desejem realizar um período de mobilidade, ou formação integral, em algumas das melhores universidades da Europa. As bolsas estão disponíveis para estudantes de graduação e doutorado, pesquisadores em pós-doutorado e pessoal acadêmico e administrativo e incluem um pagamento mensal, viagem de ida e volta, seguro e taxas de matrícula.&lt;img src=&quot;https://reinter2.furg.br/images/slider_photo_1.jpg&quot; alt=&quot;slider photo 1&quot; /&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt;O projeto Euro-Brazilian Windows + tem &amp;nbsp;o apoio financeiro atribuído pela Comissão Europeia através do Programa Erasmus Mundus e oferece bolsas a estudantes, pesquisadores e pessoal acadêmico e administrativo do Brasil que desejem realizar um período de mobilidade, ou formação integral, em algumas das melhores universidades da Europa. As bolsas estão disponíveis para estudantes de graduação e doutorado, pesquisadores em pós-doutorado e pessoal acadêmico e administrativo e incluem um pagamento mensal, viagem de ida e volta, seguro e taxas de matrícula.&lt;img src=&quot;https://reinter2.furg.br/images/slider_photo_1.jpg&quot; alt=&quot;slider photo 1&quot; /&gt;&lt;/p&gt;</content>
		<category term="destaque" />
	</entry>
	<entry>
		<title>2016 Brazilian EducationUSA Roadshow</title>
		<link rel="alternate" type="text/html" href="https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=14&amp;catid=24&amp;Itemid=137"/>
		<published>2016-03-31T18:22:14-03:00</published>
		<updated>2016-03-31T18:22:14-03:00</updated>
		<id>https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=14&amp;catid=24&amp;Itemid=137</id>
		<summary type="html">&lt;div class=&quot;featured-title&quot;&gt;Feira EducationUSA 2016&lt;/div&gt;
&lt;div class=&quot;featured-excerpt&quot;&gt;
&lt;p&gt;Tudo sobre gradua&amp;ccedil;&amp;atilde;o, mestrado, doutorado e cursos de ingl&amp;ecirc;s nos Estados Unidos!&lt;br /&gt; 8 de Abril - Belo Horizonte&lt;br /&gt; 10 de Abril - Porto Alegre&lt;br /&gt; 12 de Abril - Campinas&lt;br /&gt; 14 de Abril - Salvador&lt;br /&gt; 16 de Abril - Recife&lt;br /&gt; 17 de Abril - Fortaleza&lt;/p&gt;
&lt;/div&gt;</summary>
		<content type="html">&lt;div class=&quot;featured-title&quot;&gt;Feira EducationUSA 2016&lt;/div&gt;
&lt;div class=&quot;featured-excerpt&quot;&gt;
&lt;p&gt;Tudo sobre gradua&amp;ccedil;&amp;atilde;o, mestrado, doutorado e cursos de ingl&amp;ecirc;s nos Estados Unidos!&lt;br /&gt; 8 de Abril - Belo Horizonte&lt;br /&gt; 10 de Abril - Porto Alegre&lt;br /&gt; 12 de Abril - Campinas&lt;br /&gt; 14 de Abril - Salvador&lt;br /&gt; 16 de Abril - Recife&lt;br /&gt; 17 de Abril - Fortaleza&lt;/p&gt;
&lt;/div&gt;</content>
		<category term="destaque" />
	</entry>
	<entry>
		<title>Programa Santander Bolsas Ibero-Americanas e Luso-Brasileiras</title>
		<link rel="alternate" type="text/html" href="https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=13&amp;catid=24&amp;Itemid=137"/>
		<published>2016-03-31T17:39:07-03:00</published>
		<updated>2016-03-31T17:39:07-03:00</updated>
		<id>https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=13&amp;catid=24&amp;Itemid=137</id>
		<summary type="html">&lt;table border=&quot;0&quot; style=&quot;color: #000000; font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; margin-top: 3px; background-color: #ffffff; width: 100%;&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td class=&quot;textoNoticia&quot; style=&quot;padding-left: 5px; padding-top: 5px; font-size: 13px; color: #4f4f4f; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-align: justify; line-height: 16.9px;&quot;&gt;
&lt;p&gt;A&lt;a href=&quot;http://prograd.furg.br/&quot; target=&quot;_blank&quot; style=&quot;font-size: 12px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 0px;&quot;&gt;Pr&amp;oacute;-Reitoria de Gradua&amp;ccedil;&amp;atilde;o&lt;/a&gt;(Prograd) e a Assessoria de Rela&amp;ccedil;&amp;otilde;es Internacionais (Reinter) da Universidade Federal do Rio Grande (FURG) divulgam nesta segunda-feira (28)&amp;nbsp;o edital para acesso a&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;edi&amp;ccedil;&amp;atilde;o de 2016&lt;strong&gt;do Programa de Mobilidade Internacional do Santander Universidades nas Bolsas Luso-Brasileiras e Ibero-Americanas&lt;/strong&gt;. O edital, a declara&amp;ccedil;&amp;atilde;o de aceite, a ficha de inscri&amp;ccedil;&amp;atilde;o e os anexos podem ser acessados nos links abaixo.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;a href=&quot;http://www.furg.br/index.php?id_noticia=27031&quot; target=&quot;_blank&quot; style=&quot;font-size: 12px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 0px;&quot;&gt;Leia mais: Abertas inscri&amp;ccedil;&amp;otilde;es para Programa Mobilidade Internacional do Santander Universidades&lt;/a&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&lt;a href=&quot;http://sistemas.furg.br/sistemas/paginaFURG/arquivos/noticias/000027130000001052.pdf&quot; target=&quot;_blank&quot; class=&quot;linksNoticiasConteudo&quot; style=&quot;font-size: 13px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 5px;&quot;&gt;Edital&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&lt;a href=&quot;http://sistemas.furg.br/sistemas/paginaFURG/arquivos/noticias/000027130000001053.pdf&quot; target=&quot;_blank&quot; class=&quot;linksNoticiasConteudo&quot; style=&quot;font-size: 13px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 5px;&quot;&gt;Declara&amp;ccedil;&amp;atilde;o de aceite&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&lt;a href=&quot;http://sistemas.furg.br/sistemas/paginaFURG/arquivos/noticias/000027130000001055.pdf&quot; target=&quot;_blank&quot; class=&quot;linksNoticiasConteudo&quot; style=&quot;font-size: 13px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 5px;&quot;&gt;Anexo 2&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&lt;a href=&quot;http://sistemas.furg.br/sistemas/paginaFURG/arquivos/noticias/000027130000001056.pdf&quot; target=&quot;_blank&quot; class=&quot;linksNoticiasConteudo&quot; style=&quot;font-size: 13px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 5px;&quot;&gt;Ficha de inscri&amp;ccedil;&amp;atilde;o&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&lt;a href=&quot;http://sistemas.furg.br/sistemas/paginaFURG/arquivos/noticias/000027130000001059.pdf&quot; target=&quot;_blank&quot; class=&quot;linksNoticiasConteudo&quot; style=&quot;font-size: 13px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 5px;&quot;&gt;Anexo 1&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;</summary>
		<content type="html">&lt;table border=&quot;0&quot; style=&quot;color: #000000; font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; margin-top: 3px; background-color: #ffffff; width: 100%;&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td class=&quot;textoNoticia&quot; style=&quot;padding-left: 5px; padding-top: 5px; font-size: 13px; color: #4f4f4f; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-align: justify; line-height: 16.9px;&quot;&gt;
&lt;p&gt;A&lt;a href=&quot;http://prograd.furg.br/&quot; target=&quot;_blank&quot; style=&quot;font-size: 12px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 0px;&quot;&gt;Pr&amp;oacute;-Reitoria de Gradua&amp;ccedil;&amp;atilde;o&lt;/a&gt;(Prograd) e a Assessoria de Rela&amp;ccedil;&amp;otilde;es Internacionais (Reinter) da Universidade Federal do Rio Grande (FURG) divulgam nesta segunda-feira (28)&amp;nbsp;o edital para acesso a&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;edi&amp;ccedil;&amp;atilde;o de 2016&lt;strong&gt;do Programa de Mobilidade Internacional do Santander Universidades nas Bolsas Luso-Brasileiras e Ibero-Americanas&lt;/strong&gt;. O edital, a declara&amp;ccedil;&amp;atilde;o de aceite, a ficha de inscri&amp;ccedil;&amp;atilde;o e os anexos podem ser acessados nos links abaixo.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;a href=&quot;http://www.furg.br/index.php?id_noticia=27031&quot; target=&quot;_blank&quot; style=&quot;font-size: 12px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 0px;&quot;&gt;Leia mais: Abertas inscri&amp;ccedil;&amp;otilde;es para Programa Mobilidade Internacional do Santander Universidades&lt;/a&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&lt;a href=&quot;http://sistemas.furg.br/sistemas/paginaFURG/arquivos/noticias/000027130000001052.pdf&quot; target=&quot;_blank&quot; class=&quot;linksNoticiasConteudo&quot; style=&quot;font-size: 13px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 5px;&quot;&gt;Edital&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&lt;a href=&quot;http://sistemas.furg.br/sistemas/paginaFURG/arquivos/noticias/000027130000001053.pdf&quot; target=&quot;_blank&quot; class=&quot;linksNoticiasConteudo&quot; style=&quot;font-size: 13px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 5px;&quot;&gt;Declara&amp;ccedil;&amp;atilde;o de aceite&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&lt;a href=&quot;http://sistemas.furg.br/sistemas/paginaFURG/arquivos/noticias/000027130000001055.pdf&quot; target=&quot;_blank&quot; class=&quot;linksNoticiasConteudo&quot; style=&quot;font-size: 13px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 5px;&quot;&gt;Anexo 2&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&lt;a href=&quot;http://sistemas.furg.br/sistemas/paginaFURG/arquivos/noticias/000027130000001056.pdf&quot; target=&quot;_blank&quot; class=&quot;linksNoticiasConteudo&quot; style=&quot;font-size: 13px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 5px;&quot;&gt;Ficha de inscri&amp;ccedil;&amp;atilde;o&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td class=&quot;celulaLinksNoticias&quot; style=&quot;padding-left: 5px; padding-top: 10px;&quot;&gt;&lt;a href=&quot;http://sistemas.furg.br/sistemas/paginaFURG/arquivos/noticias/000027130000001059.pdf&quot; target=&quot;_blank&quot; class=&quot;linksNoticiasConteudo&quot; style=&quot;font-size: 13px; color: blue; font-weight: normal; font-family: Arial,Helvetica,Verdana,sans-serif; text-decoration: none; margin-right: 5px;&quot;&gt;Anexo 1&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;</content>
		<category term="destaque" />
	</entry>
	<entry>
		<title>Feira de intercâmbio especializada na Austrália e Nova Zelândia</title>
		<link rel="alternate" type="text/html" href="https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=12&amp;catid=24&amp;Itemid=137"/>
		<published>2016-03-30T19:48:08-03:00</published>
		<updated>2016-03-30T19:48:08-03:00</updated>
		<id>https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=12&amp;catid=24&amp;Itemid=137</id>
		<summary type="html">&lt;p&gt;&lt;img src=&quot;https://reinter2.furg.br/images/australia.png&quot; alt=&quot;australia&quot; /&gt;No m&amp;ecirc;s de abril de 2016 acontece a Feira de Interc&amp;acirc;mbio Especializada na Austr&amp;aacute;lia e na Nova Zel&amp;acirc;ndia.&lt;/p&gt;
&lt;p&gt;Os estudantes de todas as &amp;aacute;reas do conhecimento, que t&amp;ecirc;m interesse em realizar algum tipo de experi&amp;ecirc;ncia no exterior est&amp;atilde;o convidados a participar da feira.&lt;/p&gt;
&lt;p&gt;Durante a feira, os visitantes encontrar&amp;atilde;o institui&amp;ccedil;&amp;otilde;es de ensino e escolas de alta qualidade, algumas eleitas entre as melhores do mundo e poder&amp;atilde;o, tamb&amp;eacute;m, obter informa&amp;ccedil;&amp;otilde;es sobre como estudar e trabalhar no exterior.&lt;/p&gt;
&lt;p&gt;Para participar &amp;eacute; necess&amp;aacute;rio se inscrever no site do evento atrav&amp;eacute;s do link.&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt;&lt;img src=&quot;https://reinter2.furg.br/images/australia.png&quot; alt=&quot;australia&quot; /&gt;No m&amp;ecirc;s de abril de 2016 acontece a Feira de Interc&amp;acirc;mbio Especializada na Austr&amp;aacute;lia e na Nova Zel&amp;acirc;ndia.&lt;/p&gt;
&lt;p&gt;Os estudantes de todas as &amp;aacute;reas do conhecimento, que t&amp;ecirc;m interesse em realizar algum tipo de experi&amp;ecirc;ncia no exterior est&amp;atilde;o convidados a participar da feira.&lt;/p&gt;
&lt;p&gt;Durante a feira, os visitantes encontrar&amp;atilde;o institui&amp;ccedil;&amp;otilde;es de ensino e escolas de alta qualidade, algumas eleitas entre as melhores do mundo e poder&amp;atilde;o, tamb&amp;eacute;m, obter informa&amp;ccedil;&amp;otilde;es sobre como estudar e trabalhar no exterior.&lt;/p&gt;
&lt;p&gt;Para participar &amp;eacute; necess&amp;aacute;rio se inscrever no site do evento atrav&amp;eacute;s do link.&lt;/p&gt;</content>
		<category term="destaque" />
	</entry>
	<entry>
		<title>Bolsa Emerging Leaders in the Americas Program (ELAP) para o ano acadêmico de 2016 a 2017</title>
		<link rel="alternate" type="text/html" href="https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=11&amp;catid=24&amp;Itemid=137"/>
		<published>2016-03-24T12:55:45-03:00</published>
		<updated>2016-03-24T12:55:45-03:00</updated>
		<id>https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=11&amp;catid=24&amp;Itemid=137</id>
		<summary type="html">&lt;p style=&quot;text-align: justify; line-height: 115%;&quot;&gt;Est&amp;atilde;o abertas as inscri&amp;ccedil;&amp;otilde;es para a bolsa &lt;strong&gt;&lt;a href=&quot;http://www.scholarships-bourses.gc.ca/scholarships-bourses/can/institutions/elap-pfla.aspx?lang=eng&quot; target=&quot;_blank&quot;&gt;Emerging Leaders in the Americas Program (ELAP)&lt;/a&gt;&lt;/strong&gt; para o ano acad&amp;ecirc;mico de 2016 a 2017. Esta &amp;eacute; uma bolsa oferecida pelo governo canadense com o intuito de incentivar as pesquisas acad&amp;ecirc;micas de estudantes e pesquisadores de gradua&amp;ccedil;&amp;atilde;o e p&amp;oacute;s-gradua&amp;ccedil;&amp;atilde;o, por meio de um interc&amp;acirc;mbio acad&amp;ecirc;mico de curto per&amp;iacute;odo.&lt;/p&gt;
&lt;p style=&quot;text-align: justify; line-height: 115%;&quot;&gt;O prazo para as inscri&amp;ccedil;&amp;otilde;es desta bolsa se &lt;strong&gt;encerra em 29 de abril de 2016 &lt;/strong&gt;e a candidatura deve ser apresentada por uma universidade canadense em nome do estudante.&lt;/p&gt;
&lt;p&gt;Interessado em saber detalhes a respeito do processo? Gostaria de enviar sua pergunta?&amp;nbsp;&lt;/p&gt;
&lt;p style=&quot;margin-left: 30px; text-align: justify; line-height: 115%;&quot;&gt;&lt;strong&gt;Assista a nossa S&amp;eacute;rie de Entrevistas &amp;ndash; ELAP&lt;/strong&gt;&lt;/p&gt;
&lt;p style=&quot;margin-left: 30px; text-align: justify; line-height: 115%;&quot;&gt;Estaremos promovendo uma s&amp;eacute;rie de entrevistas sobre o programa ELAP. Iremos conversar com Elapers que j&amp;aacute; participaram do programa e um representante da embaixada canadense no Brasil para dar dicas valios&amp;iacute;ssimas. N&amp;atilde;o perca esta oportunidade de se informar sobre essa importante bolsa canadense!&lt;/p&gt;
&lt;p style=&quot;margin-left: 30px; text-align: justify; line-height: 115%;&quot;&gt;&lt;strong&gt;Para participar, clique no link abaixo agora!&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 12pt; font-family: 'Times New Roman',serif;&quot;&gt;&lt;a href=&quot;http://www.alumnicanadabrasil.org/goelap&quot; target=&quot;_blank&quot;&gt;www.alumnicanadabrasil.org/goelap&lt;/a&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;p style=&quot;text-align: justify; line-height: 115%;&quot;&gt;Est&amp;atilde;o abertas as inscri&amp;ccedil;&amp;otilde;es para a bolsa &lt;strong&gt;&lt;a href=&quot;http://www.scholarships-bourses.gc.ca/scholarships-bourses/can/institutions/elap-pfla.aspx?lang=eng&quot; target=&quot;_blank&quot;&gt;Emerging Leaders in the Americas Program (ELAP)&lt;/a&gt;&lt;/strong&gt; para o ano acad&amp;ecirc;mico de 2016 a 2017. Esta &amp;eacute; uma bolsa oferecida pelo governo canadense com o intuito de incentivar as pesquisas acad&amp;ecirc;micas de estudantes e pesquisadores de gradua&amp;ccedil;&amp;atilde;o e p&amp;oacute;s-gradua&amp;ccedil;&amp;atilde;o, por meio de um interc&amp;acirc;mbio acad&amp;ecirc;mico de curto per&amp;iacute;odo.&lt;/p&gt;
&lt;p style=&quot;text-align: justify; line-height: 115%;&quot;&gt;O prazo para as inscri&amp;ccedil;&amp;otilde;es desta bolsa se &lt;strong&gt;encerra em 29 de abril de 2016 &lt;/strong&gt;e a candidatura deve ser apresentada por uma universidade canadense em nome do estudante.&lt;/p&gt;
&lt;p&gt;Interessado em saber detalhes a respeito do processo? Gostaria de enviar sua pergunta?&amp;nbsp;&lt;/p&gt;
&lt;p style=&quot;margin-left: 30px; text-align: justify; line-height: 115%;&quot;&gt;&lt;strong&gt;Assista a nossa S&amp;eacute;rie de Entrevistas &amp;ndash; ELAP&lt;/strong&gt;&lt;/p&gt;
&lt;p style=&quot;margin-left: 30px; text-align: justify; line-height: 115%;&quot;&gt;Estaremos promovendo uma s&amp;eacute;rie de entrevistas sobre o programa ELAP. Iremos conversar com Elapers que j&amp;aacute; participaram do programa e um representante da embaixada canadense no Brasil para dar dicas valios&amp;iacute;ssimas. N&amp;atilde;o perca esta oportunidade de se informar sobre essa importante bolsa canadense!&lt;/p&gt;
&lt;p style=&quot;margin-left: 30px; text-align: justify; line-height: 115%;&quot;&gt;&lt;strong&gt;Para participar, clique no link abaixo agora!&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 12pt; font-family: 'Times New Roman',serif;&quot;&gt;&lt;a href=&quot;http://www.alumnicanadabrasil.org/goelap&quot; target=&quot;_blank&quot;&gt;www.alumnicanadabrasil.org/goelap&lt;/a&gt; &lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;</content>
		<category term="destaque" />
	</entry>
	<entry>
		<title>Cursos de verão e bolsa de estudos na Inglaterra</title>
		<link rel="alternate" type="text/html" href="https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=10&amp;catid=24&amp;Itemid=137"/>
		<published>2016-03-22T20:57:17-03:00</published>
		<updated>2016-03-22T20:57:17-03:00</updated>
		<id>https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=10&amp;catid=24&amp;Itemid=137</id>
		<summary type="html">&lt;p style=&quot;border: 0px none; font-family: body-font; font-size: 14.4px; font-style: normal; font-weight: 300; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; color: #373737; font-variant: normal; letter-spacing: normal; line-height: 23.4px; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-align: justify; background-color: #ffffff;&quot;&gt;A Universidade de Exeter estar&amp;aacute; oferecendo onze cursos de ver&amp;atilde;o com dura&amp;ccedil;&amp;atilde;o de quatro semanas para 05 estudantes brasileiros ou colombianos, como parte dos programas internacionais de ver&amp;atilde;o 2016.&lt;/p&gt;
&lt;p style=&quot;border: 0px none; font-family: body-font; font-size: 14.4px; font-style: normal; font-weight: 300; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; color: #373737; font-variant: normal; letter-spacing: normal; line-height: 23.4px; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-align: justify; background-color: #ffffff;&quot;&gt;O instituto de ver&amp;atilde;o &amp;eacute; totalmente financiado pelo Santander Universidades, cujas bolsas de estudo cobrir&amp;atilde;o taxas escolares, alojamento, a maioria das refei&amp;ccedil;&amp;otilde;es e taxas de programas sociais. Os selecionados precisar&amp;atilde;o arcar com passagens a&amp;eacute;reas, almo&amp;ccedil;os e outros itens pessoais.&lt;/p&gt;
&lt;p style=&quot;border: 0px none; font-family: body-font; font-size: 14.4px; font-style: normal; font-weight: 300; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; color: #373737; font-variant: normal; letter-spacing: normal; line-height: 23.4px; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-align: justify; background-color: #ffffff;&quot;&gt;As inscri&amp;ccedil;&amp;otilde;es se encerram em 1&amp;deg; de mar&amp;ccedil;o e podem ser aqui feitas &lt;a href=&quot;http://www.exeter.ac.uk/international/summerschool/applicationform/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;aqui&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot;border: 0px none; font-family: body-font; font-size: 14.4px; font-style: normal; font-weight: 300; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; color: #373737; font-variant: normal; letter-spacing: normal; line-height: 23.4px; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-align: justify; background-color: #ffffff;&quot;&gt;Para mais informa&amp;ccedil;&amp;otilde;es sobre o programa, acesse a &lt;a href=&quot;http://www.exeter.ac.uk/international/summerschool/santandersummerinstitute/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;p&amp;aacute;gina do instituto&lt;/a&gt;e dos &lt;a href=&quot;http://www.exeter.ac.uk/international/summerschool/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;cursos dispon&amp;iacute;veis&lt;/a&gt;.&lt;/p&gt;</summary>
		<content type="html">&lt;p style=&quot;border: 0px none; font-family: body-font; font-size: 14.4px; font-style: normal; font-weight: 300; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; color: #373737; font-variant: normal; letter-spacing: normal; line-height: 23.4px; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-align: justify; background-color: #ffffff;&quot;&gt;A Universidade de Exeter estar&amp;aacute; oferecendo onze cursos de ver&amp;atilde;o com dura&amp;ccedil;&amp;atilde;o de quatro semanas para 05 estudantes brasileiros ou colombianos, como parte dos programas internacionais de ver&amp;atilde;o 2016.&lt;/p&gt;
&lt;p style=&quot;border: 0px none; font-family: body-font; font-size: 14.4px; font-style: normal; font-weight: 300; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; color: #373737; font-variant: normal; letter-spacing: normal; line-height: 23.4px; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-align: justify; background-color: #ffffff;&quot;&gt;O instituto de ver&amp;atilde;o &amp;eacute; totalmente financiado pelo Santander Universidades, cujas bolsas de estudo cobrir&amp;atilde;o taxas escolares, alojamento, a maioria das refei&amp;ccedil;&amp;otilde;es e taxas de programas sociais. Os selecionados precisar&amp;atilde;o arcar com passagens a&amp;eacute;reas, almo&amp;ccedil;os e outros itens pessoais.&lt;/p&gt;
&lt;p style=&quot;border: 0px none; font-family: body-font; font-size: 14.4px; font-style: normal; font-weight: 300; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; color: #373737; font-variant: normal; letter-spacing: normal; line-height: 23.4px; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-align: justify; background-color: #ffffff;&quot;&gt;As inscri&amp;ccedil;&amp;otilde;es se encerram em 1&amp;deg; de mar&amp;ccedil;o e podem ser aqui feitas &lt;a href=&quot;http://www.exeter.ac.uk/international/summerschool/applicationform/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;aqui&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot;border: 0px none; font-family: body-font; font-size: 14.4px; font-style: normal; font-weight: 300; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; color: #373737; font-variant: normal; letter-spacing: normal; line-height: 23.4px; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-align: justify; background-color: #ffffff;&quot;&gt;Para mais informa&amp;ccedil;&amp;otilde;es sobre o programa, acesse a &lt;a href=&quot;http://www.exeter.ac.uk/international/summerschool/santandersummerinstitute/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;p&amp;aacute;gina do instituto&lt;/a&gt;e dos &lt;a href=&quot;http://www.exeter.ac.uk/international/summerschool/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;cursos dispon&amp;iacute;veis&lt;/a&gt;.&lt;/p&gt;</content>
		<category term="destaque" />
	</entry>
	<entry>
		<title>Escola de Verão da Universidade Bauhaus / Alemanha</title>
		<link rel="alternate" type="text/html" href="https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=9&amp;catid=24&amp;Itemid=137"/>
		<published>2016-03-22T20:52:42-03:00</published>
		<updated>2016-03-22T20:52:42-03:00</updated>
		<id>https://reinter2.furg.br/index.php?option=com_content&amp;view=article&amp;id=9&amp;catid=24&amp;Itemid=137</id>
		<summary type="html">&lt;p style=&quot;border: 0px none; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; text-align: justify;&quot;&gt;A &lt;a href=&quot;https://www.uni-weimar.de/summerschool/en/home/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;Universidade Bauhaus&lt;/a&gt;, localizada na cidade de Weimar (Alemanha), est&amp;aacute; com inscri&amp;ccedil;&amp;otilde;es abertas para a &lt;strong style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: bold; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline;&quot;&gt;Escola&lt;/strong&gt;&amp;nbsp;&lt;strong style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: bold; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline;&quot;&gt;de Ver&amp;atilde;o &lt;/strong&gt;que vai acontecer entre os dias &lt;strong style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: bold; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline;&quot;&gt;7 de agosto e 2 de setembro de 2016&lt;/strong&gt;. Ser&amp;atilde;o oferecidos cursos em v&amp;aacute;rias &amp;aacute;reas do conhecimento e cursos para o aperfei&amp;ccedil;oamento de l&amp;iacute;nguas estrangeiras.&lt;/p&gt;
&lt;p style=&quot;border: 0px none; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; text-align: justify;&quot;&gt;Os interessados podem consultar informa&amp;ccedil;&amp;otilde;es a respeito do &lt;a href=&quot;https://www.uni-weimar.de/summerschool/en/courses/overview/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;conte&amp;uacute;do do curso&lt;/a&gt;,&amp;nbsp;&lt;a href=&quot;https://www.uni-weimar.de/summerschool/en/housing/overview/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;taxas de acomoda&amp;ccedil;&amp;atilde;o &lt;/a&gt;e outras informa&amp;ccedil;&amp;otilde;es para se candidatar no &lt;a href=&quot;https://www.uni-weimar.de/summerschool/en&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;site da Universidade&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot;border: 0px none; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; text-align: justify;&quot;&gt;O prazo final de candidatura &amp;eacute; diferente para cada tipo de curso, variando entre&lt;strong style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: bold; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline;&quot;&gt;1 de Maio e 15 de Junho,&lt;/strong&gt;portanto, o candidato deve acessar o site da Universidade para conferir o prazo de inscri&amp;ccedil;&amp;atilde;o do curso desejado.&lt;/p&gt;</summary>
		<content type="html">&lt;p style=&quot;border: 0px none; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; text-align: justify;&quot;&gt;A &lt;a href=&quot;https://www.uni-weimar.de/summerschool/en/home/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;Universidade Bauhaus&lt;/a&gt;, localizada na cidade de Weimar (Alemanha), est&amp;aacute; com inscri&amp;ccedil;&amp;otilde;es abertas para a &lt;strong style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: bold; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline;&quot;&gt;Escola&lt;/strong&gt;&amp;nbsp;&lt;strong style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: bold; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline;&quot;&gt;de Ver&amp;atilde;o &lt;/strong&gt;que vai acontecer entre os dias &lt;strong style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: bold; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline;&quot;&gt;7 de agosto e 2 de setembro de 2016&lt;/strong&gt;. Ser&amp;atilde;o oferecidos cursos em v&amp;aacute;rias &amp;aacute;reas do conhecimento e cursos para o aperfei&amp;ccedil;oamento de l&amp;iacute;nguas estrangeiras.&lt;/p&gt;
&lt;p style=&quot;border: 0px none; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; text-align: justify;&quot;&gt;Os interessados podem consultar informa&amp;ccedil;&amp;otilde;es a respeito do &lt;a href=&quot;https://www.uni-weimar.de/summerschool/en/courses/overview/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;conte&amp;uacute;do do curso&lt;/a&gt;,&amp;nbsp;&lt;a href=&quot;https://www.uni-weimar.de/summerschool/en/housing/overview/&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;taxas de acomoda&amp;ccedil;&amp;atilde;o &lt;/a&gt;e outras informa&amp;ccedil;&amp;otilde;es para se candidatar no &lt;a href=&quot;https://www.uni-weimar.de/summerschool/en&quot; style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline; color: #b70e0c; text-decoration: none;&quot;&gt;site da Universidade&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot;border: 0px none; font-size: 14.4px; font-style: inherit; font-weight: inherit; margin: 0px 0px 1.625em; outline: 0px none; padding: 0px; vertical-align: baseline; text-align: justify;&quot;&gt;O prazo final de candidatura &amp;eacute; diferente para cada tipo de curso, variando entre&lt;strong style=&quot;border: 0px none; font-family: inherit; font-size: 14.4px; font-style: inherit; font-weight: bold; margin: 0px; outline: 0px none; padding: 0px; vertical-align: baseline;&quot;&gt;1 de Maio e 15 de Junho,&lt;/strong&gt;portanto, o candidato deve acessar o site da Universidade para conferir o prazo de inscri&amp;ccedil;&amp;atilde;o do curso desejado.&lt;/p&gt;</content>
		<category term="destaque" />
	</entry>
</feed>
